var Lobibox=Lobibox||{};
(function(){function f(a,b){this.$input=null;this.$type="prompt";this.$promptType=a;b=$.extend({},Lobibox.prompt.DEFAULT_OPTIONS,b);this.$options=this._processInput(b);this._init();this.debug(this)}function e(a){this.$type="confirm";this.$options=this._processInput(a);this._init();this.debug(this)}function g(a,b){this.$type=a;this.$options=this._processInput(b);this._init();this.debug(this)}function c(a){this.$type="progress";this.$progressBarElement=null;this.$options=this._processInput(a);this.$progress=
0;this._init();this.debug(this)}function m(a,b){this.$type=a;this.$options=this._processInput(b);this._init();this.debug(this)}Lobibox.prompt=function(a,b){return new f(a,b)};Lobibox.confirm=function(a){return new e(a)};Lobibox.progress=function(a){return new c(a)};Lobibox.error={};Lobibox.success={};Lobibox.warning={};Lobibox.info={};Lobibox.alert=function(a,b){if(-1<["success","error","warning","info"].indexOf(a))return new g(a,b)};Lobibox.window=function(a){return new m("window",a)};var d={$type:null,
$el:null,$options:null,debug:function(){this.$options.debug&&window.console.debug.apply(window.console,arguments)},_processInput:function(a){if($.isArray(a.buttons)){for(var b={},c=0;c<a.buttons.length;c++)b[a.buttons[c]]=Lobibox.base.OPTIONS.buttons[a.buttons[c]];a.buttons=b}a.customBtnClass=a.customBtnClass?a.customBtnClass:Lobibox.base.DEFAULTS.customBtnClass;for(c in a.buttons)a.buttons.hasOwnProperty(c)&&(b=a.buttons[c],b=$.extend({},Lobibox.base.OPTIONS.buttons[c],b),b["class"]||(b["class"]=
a.customBtnClass),a.buttons[c]=b);a=$.extend({},Lobibox.base.DEFAULTS,a);void 0===a.showClass&&(a.showClass=Lobibox.base.OPTIONS.showClass);void 0===a.hideClass&&(a.hideClass=Lobibox.base.OPTIONS.hideClass);void 0===a.baseClass&&(a.baseClass=Lobibox.base.OPTIONS.baseClass);void 0===a.delayToRemove&&(a.delayToRemove=Lobibox.base.OPTIONS.delayToRemove);a.iconClass||(a.iconClass=Lobibox.base.OPTIONS.icons[a.iconSource][this.$type]);return a},_init:function(){var a=this;a._createMarkup();a.setTitle(a.$options.title);
a.$options.draggable&&!a._isMobileScreen()&&(a.$el.addClass("draggable"),a._enableDrag());a.$options.closeButton&&a._addCloseButton();if(a.$options.closeOnEsc)$(document).on("keyup.lobibox",function(b){27===b.which&&a.destroy()});a.$options.baseClass&&a.$el.addClass(a.$options.baseClass);a.$options.showClass&&(a.$el.removeClass(a.$options.hideClass),a.$el.addClass(a.$options.showClass));a.$el.data("lobibox",a)},_calculatePosition:function(a){a="top"===a?30:"bottom"===a?$(window).outerHeight()-this.$el.outerHeight()-
30:($(window).outerHeight()-this.$el.outerHeight())/2;return{left:($(window).outerWidth()-this.$el.outerWidth())/2,top:a}},_createButton:function(a,b){var c=this,d=$("<button></button>").addClass(b["class"]).attr("data-type",a).html(b.text);if(c.$options.callback&&"function"===typeof c.$options.callback)d.on("click.lobibox",function(b){var h=$(this);c.$options.buttons[a]&&c.$options.buttons[a].closeOnClick&&c.destroy();c.$options.callback(c,h.data("type"),b)});d.click(function(){c.$options.buttons[a]&&
c.$options.buttons[a].closeOnClick&&c.destroy()});return d},_generateButtons:function(){var a=[],b;for(b in this.$options.buttons)if(this.$options.buttons.hasOwnProperty(b)){var c=this._createButton(b,this.$options.buttons[b]);a.push(c)}return a},_createMarkup:function(){var a=$('<div class="lobibox"></div>');a.attr("data-is-modal",this.$options.modal);var b=$('<div class="lobibox-header"></div>').append('<span class="lobibox-title"></span>'),c=$('<div class="lobibox-body"></div>');a.append(b);a.append(c);
this.$options.buttons&&!$.isEmptyObject(this.$options.buttons)&&(b=$('<div class="lobibox-footer"></div>'),b.append(this._generateButtons()),a.append(b),-1<Lobibox.base.OPTIONS.buttonsAlign.indexOf(this.$options.buttonsAlign)&&b.addClass("text-"+this.$options.buttonsAlign));this.$el=a.addClass(Lobibox.base.OPTIONS.modalClasses[this.$type])},_setSize:function(){this.setWidth(this.$options.width);"auto"===this.$options.height?this.setHeight(this.$el.outerHeight()):this.setHeight(this.$options.height)},
_calculateBodyHeight:function(a){var b=this.$el.find(".lobibox-header").outerHeight(),c=this.$el.find(".lobibox-footer").outerHeight();return a-(b?b:0)-(c?c:0)},_addBackdrop:function(){0===$(".lobibox-backdrop").length&&$("body").append('<div class="lobibox-backdrop"></div>')},_triggerEvent:function(a){if(this.$options[a]&&"function"===typeof this.$options[a])this.$options[a](this)},_calculateWidth:function(a){a=Math.min($(window).outerWidth(),a);a===$(window).outerWidth()&&(a-=2*this.$options.horizontalOffset);
return a},_calculateHeight:function(a){return Math.min($(window).outerHeight(),a)},_addCloseButton:function(){var a=this,b=$('<span class="btn-close">&times;</span>');a.$el.find(".lobibox-header").append(b);b.on("mousedown",function(a){a.stopPropagation()});b.on("click.lobibox",function(){a.destroy()})},_position:function(){this._setSize();var a=this._calculatePosition();this.setPosition(a.left,a.top)},_isMobileScreen:function(){return 768>$(window).outerWidth()},_enableDrag:function(){var a=this.$el;
a.find(".lobibox-header").on("mousedown.lobibox",function(b){a.attr("offset-left",b.offsetX);a.attr("offset-top",b.offsetY);a.attr("allow-drag","true")});$(document).on("mouseup.lobibox",function(){a.attr("allow-drag","false")});$(document).on("mousemove.lobibox",function(b){if("true"===a.attr("allow-drag")){var c=b.clientX-parseInt(a.attr("offset-left"),10)-parseInt(a.css("border-left-width"),10);b=b.clientY-parseInt(a.attr("offset-top"),10)-parseInt(a.css("border-top-width"),10);a.css({left:c,top:b})}})},
_setContent:function(a){this.$el.find(".lobibox-body").html(a);return this},hide:function(){function a(){b.$el.addClass("lobibox-hidden");0===$(".lobibox[data-is-modal=true]:not(.lobibox-hidden)").length&&($(".lobibox-backdrop").remove(),$("body").removeClass(Lobibox.base.OPTIONS.bodyClass))}var b=this;b.$options.hideClass?(b.$el.removeClass(b.$options.showClass),b.$el.addClass(b.$options.hideClass),setTimeout(function(){a()},b.$options.delayToRemove)):a();return this},destroy:function(){function a(){b.$el.remove();
0===$(".lobibox[data-is-modal=true]").length&&($(".lobibox-backdrop").remove(),$("body").removeClass(Lobibox.base.OPTIONS.bodyClass));b._triggerEvent("closed")}var b=this;b._triggerEvent("beforeClose");b.$options.hideClass?(b.$el.removeClass(b.$options.showClass).addClass(b.$options.hideClass),setTimeout(function(){a()},b.$options.delayToRemove)):a();return this},setWidth:function(a){this.$el.css("width",this._calculateWidth(a));return this},setHeight:function(a){this.$el.css("height",this._calculateHeight(a)).find(".lobibox-body").css("height",
this._calculateBodyHeight(this.$el.innerHeight()));return this},setSize:function(a,b){this.setWidth(a);this.setHeight(b);return this},setPosition:function(a,b){var c;"number"===typeof a&&"number"===typeof b?c={left:a,top:b}:"string"===typeof a&&(c=this._calculatePosition(a));this.$el.css(c);return this},setTitle:function(a){return this.$el.find(".lobibox-title").html(a)},getTitle:function(){return this.$el.find(".lobibox-title").html()},show:function(){var a=$("body");this._triggerEvent("onShow");
this.$el.removeClass("lobibox-hidden");a.append(this.$el);this.$options.buttons&&this.$el.find(".lobibox-footer").children()[0].focus();this.$options.modal&&(a.addClass(Lobibox.base.OPTIONS.bodyClass),this._addBackdrop());this._triggerEvent("shown");return this}};Lobibox.base={};Lobibox.base.OPTIONS={bodyClass:"lobibox-open",modalClasses:{error:"lobibox-error",success:"lobibox-success",info:"lobibox-info",warning:"lobibox-warning",confirm:"lobibox-confirm",progress:"lobibox-progress",prompt:"lobibox-prompt",
"default":"lobibox-default",window:"lobibox-window"},buttonsAlign:["left","center","right"],buttons:{ok:{"class":"lobibox-btn lobibox-btn-default",text:"OK",closeOnClick:!0},cancel:{"class":"lobibox-btn lobibox-btn-cancel",text:"Cancel",closeOnClick:!0},yes:{"class":"lobibox-btn lobibox-btn-yes",text:"Yes",closeOnClick:!0},no:{"class":"lobibox-btn lobibox-btn-no",text:"No",closeOnClick:!0}},icons:{bootstrap:{confirm:"glyphicon glyphicon-question-sign",success:"glyphicon glyphicon-ok-sign",error:"glyphicon glyphicon-remove-sign",
warning:"glyphicon glyphicon-exclamation-sign",info:"glyphicon glyphicon-info-sign"},fontAwesome:{confirm:"fa fa-question-circle",success:"fa fa-check-circle",error:"fa fa-times-circle",warning:"fa fa-exclamation-circle",info:"fa fa-info-circle"}}};Lobibox.base.DEFAULTS={horizontalOffset:5,width:600,height:"auto",closeButton:!0,draggable:!1,customBtnClass:"lobibox-btn lobibox-btn-default",modal:!0,debug:!1,buttonsAlign:"center",closeOnEsc:!0,delayToRemove:200,baseClass:"animated-super-fast",showClass:"zoomIn",
hideClass:"zoomOut",iconSource:"bootstrap",onShow:null,shown:null,beforeClose:null,closed:null};f.prototype=$.extend({},d,{constructor:f,_processInput:function(a){var b=d._processInput.call(this,a);b.buttons={ok:Lobibox.base.OPTIONS.buttons.ok,cancel:Lobibox.base.OPTIONS.buttons.cancel};return a=$.extend({},b,f.DEFAULT_OPTIONS,a)},_init:function(){d._init.call(this);this.show();this._setContent(this._createInput())._position();this.$input.focus()},_createInput:function(){var a;this.$input=this.$options.multiline?
$("<textarea></textarea>").attr("rows",this.$options.lines):$('<input type="'+this.$promptType+'"/>');this.$input.addClass("lobibox-input").attr(this.$options.attrs);this.$options.value&&this.setValue(this.$options.value);this.$options.label&&(a=$("<label>"+this.$options.label+"</label>"));return $("<div></div>").append(a,this.$input)},setValue:function(a){this.$input.val(a);return this},getValue:function(){return this.$input.val()}});f.DEFAULT_OPTIONS={width:400,attrs:{},value:"",multiline:!1,lines:3,
type:"text",label:""};e.prototype=$.extend({},d,{constructor:e,_processInput:function(a){var b=d._processInput.call(this,a);b.buttons={yes:Lobibox.base.OPTIONS.buttons.yes,no:Lobibox.base.OPTIONS.buttons.no};return a=$.extend({},b,Lobibox.confirm.DEFAULTS,a)},_init:function(){d._init.call(this);this.show();var a=$("<div></div>");this.$options.iconClass&&a.append($('<div class="lobibox-icon-wrapper"></div>').append('<i class="lobibox-icon '+this.$options.iconClass+'"></i>'));a.append('<div class="lobibox-body-text-wrapper"><span class="lobibox-body-text">'+
this.$options.msg+"</span></div>");this._setContent(a.html());this._position()}});Lobibox.confirm.DEFAULTS={title:"Question",width:500};g.prototype=$.extend({},d,{constructor:g,_processInput:function(a){var b=d._processInput.call(this,a);b.buttons={ok:Lobibox.base.OPTIONS.buttons.ok};return a=$.extend({},b,Lobibox.alert.OPTIONS[this.$type],Lobibox.alert.DEFAULTS,a)},_init:function(){d._init.call(this);this.show();var a=$("<div></div>");this.$options.iconClass&&a.append($('<div class="lobibox-icon-wrapper"></div>').append('<i class="lobibox-icon '+
this.$options.iconClass+'"></i>'));a.append('<div class="lobibox-body-text-wrapper"><span class="lobibox-body-text">'+this.$options.msg+"</span></div>");this._setContent(a.html());this._position()}});Lobibox.alert.OPTIONS={warning:{title:"Warning"},info:{title:"Information"},success:{title:"Success"},error:{title:"Error"}};Lobibox.alert.DEFAULTS={};c.prototype=$.extend({},d,{constructor:c,_processInput:function(a){var b=d._processInput.call(this,a);return a=$.extend({},b,Lobibox.progress.DEFAULTS,
a)},_init:function(){d._init.call(this);this.show();this.$progressBarElement=this.$options.progressTpl?$(this.$options.progressTpl):this._createProgressbar();var a;this.$options.label&&(a=$("<label>"+this.$options.label+"</label>"));a=$("<div></div>").append(a,this.$progressBarElement);this._setContent(a);this._position()},_createProgressbar:function(){var a=$('<div class="lobibox-progress-bar-wrapper lobibox-progress-outer"></div>').append('<div class="lobibox-progress-bar lobibox-progress-element"></div>');
this.$options.showProgressLabel&&a.append('<span class="lobibox-progress-text" data-role="progress-text"></span>');return a},setProgress:function(a){if(100!==this.$progress)return this.$progress=a=Math.min(100,Math.max(0,a)),this._triggerEvent("progressUpdated"),100===this.$progress&&this._triggerEvent("progressCompleted"),this.$el.find(".lobibox-progress-element").css("width",a.toFixed(1)+"%"),this.$el.find('[data-role="progress-text"]').html(a.toFixed(1)+"%"),this},getProgress:function(){return this.$progress}});
Lobibox.progress.DEFAULTS={width:500,showProgressLabel:!0,label:"",progressTpl:!1,progressUpdated:null,progressCompleted:null};m.prototype=$.extend({},d,{constructor:m,_processInput:function(a){var b=d._processInput.call(this,a);a.content&&"function"===typeof a.content&&(a.content=a.content());a.content instanceof jQuery&&(a.content=a.content.clone());return a=$.extend({},b,Lobibox.window.DEFAULTS,a)},_init:function(){var a=this;d._init.call(a);a.setContent(a.$options.content);a.$options.url&&a.$options.autoload?
(a.$options.showAfterLoad||(a.show(),a._position()),a.load(function(){a.$options.showAfterLoad&&(a.show(),a._position())})):(a.show(),a._position())},setParams:function(a){this.$options.params=a;return this},getParams:function(){return this.$options.params},setLoadMethod:function(a){this.$options.loadMethod=a;return this},getLoadMethod:function(){return this.$options.loadMethod},setContent:function(a){this.$options.content=a;this.$el.find(".lobibox-body").html("").append(a);return this},getContent:function(){return this.$options.content},
setUrl:function(a){this.$options.url=a;return this},getUrl:function(){return this.$options.url},load:function(a){var b=this;if(!b.$options.url)return b;$.ajax(b.$options.url,{method:b.$options.loadMethod,data:b.$options.params}).done(function(c){b.setContent(c);a&&"function"===typeof a&&a(c)});return b}});Lobibox.window.DEFAULTS={width:480,height:600,content:"",url:"",draggable:!0,autoload:!0,loadMethod:"GET",showAfterLoad:!0,params:{}}})();
Math.randomString=function(f){for(var e="",g=0;g<f;g++)e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));return e};Lobibox=Lobibox||{};
(function(){var f=function(e,g){this.$el=this.$options=this.$type=null;var c=this,f=function(b,k){if("normal"===c.$options.size)k.append(b);else if("mini"===c.$options.size)b.addClass("notify-mini"),k.append(b);else if("large"===c.$options.size){var h=$("<div></div>",{"class":"lb-tab-pane",id:Math.randomString(10)}).append(b),l=a(h.attr("id"));k.find(".lb-notify-wrapper").append(h);k.find(".lb-notify-tabs").append(l);d(l);l.find(">a").click(function(){d(l)})}},d=function(a){a.closest(".lb-notify-tabs").find(">li").removeClass("active");
a.addClass("active");a=$(a.find(">a").attr("href"));a.closest(".lb-notify-wrapper").find(">.lb-tab-pane").removeClass("active");a.addClass("active")},a=function(a){var b=$("<li></li>",{"class":Lobibox.notify.OPTIONS[c.$type]["class"]});$("<a></a>",{href:"#"+a}).append('<i class="tab-control-icon '+c.$options.icon+'"></i>').appendTo(b);return b},b=function(a){c.$options.closable&&$('<span class="lobibox-close">&times;</span>').click(function(){c.remove()}).appendTo(a)},n=function(a){c.$options.closeOnClick&&
a.click(function(){c.remove()})},p=function(a){if(c.$options.delay){if(c.$options.delayIndicator){var b=$('<div class="lobibox-delay-indicator"><div></div></div>');a.append(b)}var h=0,d=1E3/30,f=setInterval(function(){h+=d;var a=100*h/c.$options.delay;100<=a&&(a=100,c.remove(),f=clearInterval(f));c.$options.delayIndicator&&b.find("div").css("width",a+"%")},d)}},q=function(a){return a=Math.min($(window).outerWidth(),a)};this.remove=function(){c.$el.removeClass(c.$options.showClass).addClass(c.$options.hideClass);
var a=c.$el.parent(),b=a.closest(".lobibox-notify-wrapper-large"),f="#"+a.attr("id"),e=b.find('>.lb-notify-tabs>li:has(a[href="'+f+'"])');e.addClass(Lobibox.notify.OPTIONS["class"]).addClass(c.$options.hideClass);setTimeout(function(){if("normal"===c.$options.size||"mini"===c.$options.size)c.$el.remove();else if("large"===c.$options.size){var b;b=e.prev();0===b.length&&(b=e.next());b=0===b.length?null:b;b&&d(b);e.remove();a.remove()}},500);return c};this.$type=e;this.$options=function(a){if("mini"===
a.size||"large"===a.size)a.width=a.width||Lobibox.notify.OPTIONS[a.size].width;a=$.extend({},Lobibox.notify.OPTIONS[c.$type],Lobibox.notify.DEFAULTS,a);"mini"!==a.size&&!0===a.title?a.title=Lobibox.notify.OPTIONS[c.$type].title:"mini"===a.size&&!0===a.title&&(a.title=!1);!0===a.icon&&(a.icon=Lobibox.notify.OPTIONS.icons[a.iconSource][c.$type]);!0===a.sound&&(a.sound=Lobibox.notify.OPTIONS[c.$type].sound);a.sound&&(a.sound=a.soundPath+a.sound+a.soundExt);return a}(g);(function(){var a=Lobibox.notify.OPTIONS,
d,a=$("<div></div>",{"class":"lobibox-notify "+a[c.$type]["class"]+" "+a["class"]+" "+c.$options.showClass});d=$('<div class="lobibox-notify-icon"></div>').appendTo(a);c.$options.img?d.append('<img src="'+c.$options.img+'"/>'):c.$options.icon?d.append('<i class="'+c.$options.icon+'"></i>'):a.addClass("without-icon");d=$("<div></div>",{"class":"lobibox-notify-body"}).append('<div class="lobibox-notify-msg">'+c.$options.msg+"</div>").appendTo(a);c.$options.title&&d.prepend('<div class="lobibox-notify-title">'+
c.$options.title+"<div>");b(a);if("normal"===c.$options.size||"mini"===c.$options.size)n(a),p(a);c.$options.width&&a.css("width",q(c.$options.width));d=("large"===c.$options.size?".lobibox-notify-wrapper-large":".lobibox-notify-wrapper")+"."+c.$options.position.replace(/\s/gi,".");var e;e=$(d);0===e.length&&(e=$("<div></div>").addClass(d.replace(/\./g," ").trim()).appendTo($("body")),"large"===c.$options.size&&e.append($('<ul class="lb-notify-tabs"></ul>')).append($('<div class="lb-notify-wrapper"></div>')));
f(a,e);c.$el=a;c.$options.sound&&(new Audio(c.$options.sound)).play();c.$el.data("lobibox",c)})()};Lobibox.notify=function(e,g){if(-1<["info","warning","error","success"].indexOf(e))return new f(e,g)};Lobibox.notify.DEFAULTS={title:!0,size:"normal",soundPath:"sounds/",soundExt:".ogg",showClass:"zoomIn",hideClass:"zoomOut",icon:!0,msg:"",img:null,closable:!0,delay:5E3,delayIndicator:!0,closeOnClick:!0,width:400,sound:!0,position:"bottom right",iconSource:"bootstrap"};Lobibox.notify.OPTIONS={"class":"animated-fast",
large:{width:500},mini:{"class":"notify-mini"},success:{"class":"lobibox-notify-success",title:"Success",sound:"sound2"},error:{"class":"lobibox-notify-error",title:"Error",sound:"sound4"},warning:{"class":"lobibox-notify-warning",title:"Warning",sound:"sound5"},info:{"class":"lobibox-notify-info",title:"Information",sound:"sound6"},icons:{bootstrap:{success:"glyphicon glyphicon-ok-sign",error:"glyphicon glyphicon-remove-sign",warning:"glyphicon glyphicon-exclamation-sign",info:"glyphicon glyphicon-info-sign"},
fontAwesome:{success:"fa fa-check-circle",error:"fa fa-times-circle",warning:"fa fa-exclamation-circle",info:"fa fa-info-circle"}}}})();